repository: HasKha/GWToolboxpp

title: GWToolbox++
description: Tools for Guild Wars
show_downloads: true
google_analytics: UA-75239620-2
theme: jekyll-theme-midnight

download_url: https://github.com/gwdevhub/GWToolboxpp/releases/download/8.3_Release/gwtoolbox.exe
discord_url: https://discord.gg/pGS5pFn
toolbox_version: "8.4"
