repository: HasKha/GWToolboxpp

title: GWToolbox++
description: Tools for Guild Wars
show_downloads: true
google_analytics: UA-75239620-2
theme: jekyll-theme-midnight

download_url: https://github.com/HasKha/GWToolboxpp/releases/download/2.6_Release/GWToolbox.exe
discord_url: https://discord.gg/pGS5pFn
toolbox_version: 2.8
